# Generated by Django 5.2.3 on 2025-06-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=20, verbose_name="Email")),
                ("country", models.CharField(max_length=20, verbose_name="Country")),
                ("city", models.CharField(max_length=50, verbose_name="City")),
                ("street", models.CharField(max_length=150, verbose_name="Street")),
                (
                    "house_number",
                    models.PositiveSmallIntegerField(verbose_name="House number"),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["email", "country"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("model", models.CharField(max_length=50, verbose_name="Model")),
                ("date_release", models.DateField(verbose_name="Date release")),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["name"],
            },
        ),
    ]
